var app = angular.module("myApp", ["ionic", "oc.lazyLoad"]).run(function($ionicPlatform, $rootScope, $ionicLoading, $state) {
	$ionicPlatform.ready(function() {
		window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard && (cordova.plugins.Keyboard.hideKeyboardAccessoryBar(!0), cordova.plugins.Keyboard.disableScroll(!0)), window.StatusBar && StatusBar.styleDefault()
	}), $rootScope.app_key = "app_key=689cf76eb3c96b7cb3ddb07e4e5efe54", $rootScope.pwd = "5ef962cdf5700cc8e97e3660ca065e72", $rootScope.data = new Date, $rootScope.open_id = 0, $rootScope.ip = "http://mopdatatest.huomanhao.com", $rootScope.isCode = "micromessenger" == navigator.userAgent.toLowerCase().match(/MicroMessenger/i) || ($rootScope.open_id = "TheBrowserToRegister", window.localStorage.open_id = $rootScope.open_id, !1), window.localStorage.isCode = $rootScope.isCode, $rootScope.access_token = null
}).config(["$stateProvider", "$ionicConfigProvider", "$urlRouterProvider", "$controllerProvider", "$compileProvider", "$filterProvider", "$provide", "$ocLazyLoadProvider", "JS_REQUIRES", "$httpProvider", function($stateProvider, $ionicConfigProvider, $urlRouterProvider, $controllerProvider, $compileProvider, $filterProvider, $provide, $ocLazyLoadProvider, jsRequires, $httpProvider) {
	function loadSequence() {
		var _args = arguments,
			viewArgs = function(name) {
				return jsRequires.ViewArgs[name]
			}(_args[0]);
		return viewArgs && (_args = viewArgs), {
			deps: ["$ocLazyLoad", "$q", function($ocLL, $q) {
				function requiredData(name) {
					if (jsRequires.modules)
						for (var m in jsRequires.modules)
							if (jsRequires.modules[m].name && jsRequires.modules[m].name === name) return jsRequires.modules[m];
					return jsRequires.scripts && jsRequires.scripts[name]
				}
				for (var promise = $q.when(1), i = 0, len = _args.length; i < len; i++) promise = function(_arg) {
					return "function" == typeof _arg ? promise.then(_arg) : promise.then(function() {
						var nowLoad = requiredData(_arg);
						return nowLoad ? $ocLL.load(nowLoad + "?366") : console.log("引入失败? [" + _arg + "]")
					})
				}(_args[i]);
				return promise
			}]
		}
	}
	app.controller = $controllerProvider.register, app.directive = $compileProvider.directive, app.filter = $filterProvider.register, app.factory = $provide.factory, app.service = $provide.service, app.constant = $provide.constant, app.value = $provide.value, $ionicConfigProvider.platform.ios.tabs.style("standard"), $ionicConfigProvider.platform.ios.tabs.position("bottom"), $ionicConfigProvider.platform.android.tabs.style("standard"), $ionicConfigProvider.platform.android.tabs.position("bottom"), $ionicConfigProvider.platform.ios.navBar.alignTitle("center"), $ionicConfigProvider.platform.android.navBar.alignTitle("center"), $ionicConfigProvider.platform.ios.backButton.previousTitleText("").icon("ion-ios-arrow-thin-left"), $ionicConfigProvider.platform.android.backButton.previousTitleText("").icon("ion-android-arrow-back"), $ionicConfigProvider.platform.ios.views.transition("ios"), $ionicConfigProvider.platform.android.views.transition("android"), $ionicConfigProvider.scrolling.jsScrolling(!1), $httpProvider.interceptors.push(function($rootScope) {
		return {
			request: function(config) {
				return $rootScope.$broadcast("loading:show"), config
			},
			response: function(response) {
				return $rootScope.$broadcast("loading:hide"), response
			}
		}
	}), $stateProvider.state("tabs", {
		url: "/tabs",
		abstract: !0,
		templateUrl: "templates/tabs/tabs.html?366",
		controller: "tabsCtrl",
		resolve: loadSequence("tabsCtrl")
	}).state("tabs.home", {
		url: "/home",
		views: {
			"tabs-home": {
				prefetchTemplate: !1,
				templateUrl: "templates/home/home.html?366",
				controller: "homeCtrl",
				resolve: loadSequence("homeCtrl")
			}
		}
	}).state("tabs.goodList", {
		cache: !0,
		url: "/goodList",
		views: {
			"tabs-goodList": {
				prefetchTemplate: !1,
				templateUrl: "templates/goodChoice/good_list.html?366",
				controller: "goodListCtrl",
				resolve: loadSequence("goodListCtrl")
			}
		}
	}).state("search", {
		cache: !1,
		url: "/search",
		prefetchTemplate: !1,
		templateUrl: "templates/search/search.html?366",
		controller: "searchCtrl",
		resolve: loadSequence("searchCtrl")
	}).state("searchResults", {
		cache: !1,
		url: "/searchResults",
		prefetchTemplate: !1,
		templateUrl: "templates/search/search_results.html?366",
		controller: "searchResultsCtrl",
		resolve: loadSequence("searchResultsCtrl")
	}).state("searchNoResults", {
		url: "/searchNoResults",
		prefetchTemplate: !1,
		templateUrl: "templates/search/search_no_results.html?366"
	}).state("olduserWelfare", {
		cache: !1,
		url: "/olduserWelfare",
		prefetchTemplate: !1,
		templateUrl: "templates/home/olduser_welfare.html?366",
		controller: "olduserWelfareCtrl",
		resolve: loadSequence("olduserWelfareCtrl")
	}).state("newpeopleWelfare", {
		cache: !1,
		url: "/newpeopleWelfare",
		prefetchTemplate: !1,
		templateUrl: "templates/home/newpeople_welfare.html?366",
		controller: "newpeopleWelfareCtrl",
		resolve: loadSequence("newpeopleWelfareCtrl")
	}).state("details", {
		cache: !1,
		url: "/details",
		prefetchTemplate: !1,
		templateUrl: "templates/details/details.html?366",
		controller: "detailsCtrl",
		resolve: loadSequence("detailsCtrl")
	}).state("highList", {
		url: "/highList",
		prefetchTemplate: !1,
		templateUrl: "templates/high/high_list.html?366",
		controller: "highListCtrl",
		resolve: loadSequence("highListCtrl")
	}).state("todayList", {
		url: "/todayList",
		prefetchTemplate: !1,
		templateUrl: "templates/today/today_list.html?366",
		controller: "todayListCtrl",
		resolve: loadSequence("todayListCtrl")
	}).state("newList", {
		url: "/newList",
		prefetchTemplate: !1,
		templateUrl: "templates/new/new_list.html?366",
		controller: "newListCtrl",
		resolve: loadSequence("newListCtrl")
	}).state("tabs.spokesmanPage", {
		cache: !1,
		url: "/spokesmanPage",
		views: {
			"tabs-spokesmanPage": {
				prefetchTemplate: !1,
				templateUrl: "templates/spokesman/spokesman_projectPage.html?366",
				controller: "spokesmanPageCtrl",
				resolve: loadSequence("spokesmanPageCtrl")
			}
		}
	}).state("tabs.spokesmanWhat", {
		cache: !1,
		url: "/spokesmanWhat",
		views: {
			"tabs-spokesmanPage": {
				prefetchTemplate: !1,
				templateUrl: "templates/spokesman/spokesman_what.html?366",
				controller: "spokesmanWhatCtrl",
				resolve: loadSequence("spokesmanWhatCtrl")
			}
		}
	}).state("spokesmanDetail", {
		params: {
			step: null
		},
		cache: !1,
		url: "/spokesmanDetail",
		prefetchTemplate: !1,
		templateUrl: "templates/spokesman/spokesman_detail.html?366",
		controller: "spokesmanDetailCtrl",
		resolve: loadSequence("spokesmanDetailCtrl")
	}).state("tabs.personalCenter", {
		url: "/personalCenter",
		views: {
			"tabs-personalCenter": {
				prefetchTemplate: !1,
				templateUrl: "templates/account/personal_center.html?366",
				controller: "personalCenterCtrl",
				resolve: loadSequence("personalCenterCtrl")
			}
		}
	}).state("gradeRank", {
		cache: !1,
		url: "/gradeRank",
		prefetchTemplate: !1,
		templateUrl: "templates/account/grade_rank.html?366",
		controller: "gradeRankCtrl",
		resolve: loadSequence("gradeRankCtrl")
	}).state("personalDate", {
		cache: !1,
		url: "/personalDate",
		prefetchTemplate: !1,
		templateUrl: "templates/account/personal_date.html?366",
		controller: "personalDateCtrl",
		resolve: loadSequence("personalDateCtrl")
	}).state("winningValue", {
		cache: !1,
		url: "/winningValue",
		prefetchTemplate: !1,
		templateUrl: "templates/account/winning_value.html?366",
		controller: "winningValueCtrl",
		resolve: loadSequence("winningValueCtrl")
	}).state("coinIndex", {
		url: "/coinIndex",
		prefetchTemplate: !1,
		templateUrl: "templates/coin/coin_index.html?366",
		controller: "coinListCtrl",
		resolve: loadSequence("coinListCtrl")
	}).state("coinSecondsKillIndex", {
		url: "/coinSecondsKillIndex",
		prefetchTemplate: !1,
		templateUrl: "templates/coin/coinSecondsKill_index.html?142",
		controller: "coinSecondsKillCtrl",
		resolve: loadSequence("coinSecondsKillCtrl")
	}).state("coinSecondsKillSuccess", {
		cache: !1,
		url: "/coinSecondsKillSuccess",
		prefetchTemplate: !1,
		templateUrl: "templates/coin/coinSecondsKill_success.html?142",
		controller: "coinSecondsKillSuccessCtrl",
		resolve: loadSequence("coinSecondsKillSuccessCtrl")
	}).state("coinSecondsKillDefeated", {
		cache: !1,
		url: "/coinSecondsKillDefeated",
		prefetchTemplate: !1,
		templateUrl: "templates/coin/coinSecondsKill_defeated.html?142",
		controller: "coinSecondsKillDefeatedCtrl",
		resolve: loadSequence("coinSecondsKillDefeatedCtrl")
	}).state("tabs.applyIndex", {
		url: "/applyIndex",
		views: {
			"tabs-applyIndex": {
				prefetchTemplate: !1,
				templateUrl: "templates/apply/apply_index.html?366",
				controller: "applyIndexCtrl",
				resolve: loadSequence("applyIndexCtrl")
			}
		}
	}).state("applyCollect", {
		cache: !1,
		url: "/applyCollect",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_collect.html?366",
		controller: "applyCollectCtrl",
		resolve: loadSequence("applyCollectCtrl")
	}).state("applyCommand", {
		cache: !1,
		url: "/applyCommand",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_command.html?366",
		controller: "applyCommandCtrl",
		resolve: loadSequence("applyCommandCtrl")
	}).state("applyPc", {
		cache: !1,
		url: "/applyPc",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_pc.html?366",
		controller: "applyPcCtrl",
		resolve: loadSequence("applyPcCtrl")
	}).state("applyQrcode", {
		cache: !1,
		url: "/applyQrcode",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_qrcode.html?366",
		controller: "applyQrcodeCtrl",
		resolve: loadSequence("applyQrcodeCtrl")
	}).state("applyCompare", {
		cache: !1,
		url: "/applyCompare",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_compare.html?366",
		controller: "applyCompareCtrl",
		resolve: loadSequence("applyCompareCtrl")
	}).state("applySameshop", {
		cache: !1,
		url: "/applySameshop",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_sameshop.html?366",
		controller: "applySameshopCtrl",
		resolve: loadSequence("applySameshopCtrl")
	}).state("applyRelevance", {
		cache: !1,
		url: "/applyRelevance",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_relevance.html?366",
		controller: "applyRelevanceCtrl",
		resolve: loadSequence("applyRelevanceCtrl")
	}).state("applyPay", {
		cache: !1,
		url: "/applyPay",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_pay.html?366",
		controller: "applyPayCtrl",
		resolve: loadSequence("applyPayCtrl")
	}).state("applyWangwangchat", {
		cache: !1,
		url: "/applyWangwangchat",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_wangwangchat.html?366",
		controller: "applyWangwangchatCtrl",
		resolve: loadSequence("applyWangwangchatCtrl")
	}).state("applyShoutao", {
		cache: !1,
		url: "/applyShoutao",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_shoutao.html?366",
		controller: "applyShoutaoCtrl",
		resolve: loadSequence("applyShoutaoCtrl")
	}).state("applyTomorrow", {
		url: "/applyTomorrow",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_tomorrow.html?366",
		controller: "applyTomorrowCtrl",
		resolve: loadSequence("applyTomorrowCtrl")
	}).state("applyFinish", {
		cache: !1,
		url: "/applyFinish",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_finish.html?366",
		controller: "applyFinishCtrl",
		resolve: loadSequence("applyFinishCtrl")
	}).state("applyComplete", {
		cache: !1,
		url: "/applyComplete",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_complete.html?366",
		controller: "applyCompleteCtrl",
		resolve: loadSequence("applyCompleteCtrl")
	}).state("applyEvaluationfinish", {
		cache: !1,
		url: "/applyEvaluationfinish",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_evaluationfinish.html?366",
		controller: "applyEvaluationfinishCtrl",
		resolve: loadSequence("applyEvaluationfinishCtrl")
	}).state("applyovertime", {
		cache: !1,
		url: "/applyovertime",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_overtime.html?366",
		controller: "applyovertimeCtrl",
		resolve: loadSequence("applyovertimeCtrl")
	}).state("applyAlreadyfull", {
		cache: !1,
		url: "/applyAlreadyfull",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_alreadyfull.html?366",
		controller: "applyalreadyfullCtrl",
		resolve: loadSequence("applyalreadyfullCtrl")
	}).state("notWinning", {
		cache: !1,
		url: "/notWinning",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/apply_nowin.html?366",
		controller: "applynowinCtrl",
		resolve: loadSequence("applynowinCtrl")
	}).state("addvalueservicesShare", {
		cache: !1,
		url: "/addvalueservicesShare",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/addvalueservices_share.html?366",
		controller: "addvalueservicesShareCtrl",
		resolve: loadSequence("addvalueservicesShareCtrl")
	}).state("addvalueservicesShowpic", {
		cache: !1,
		url: "/addvalueservicesShowpic",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/addvalueservices_showpic.html?366",
		controller: "addvalueservicesShowpicCtrl",
		resolve: loadSequence("addvalueservicesShowpicCtrl")
	}).state("addvalueservicesShowtext", {
		cache: !1,
		url: "/addvalueservicesShowtext",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/addvalueservices_showtext.html?366",
		controller: "addvalueservicesShowtextCtrl",
		resolve: loadSequence("addvalueservicesShowtextCtrl")
	}).state("addvalueservicesAddshowpic", {
		cache: !1,
		url: "/addvalueservicesAddshowpic",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/addvalueservices_addshowpic.html?366",
		controller: "addvalueservicesAddshowpicCtrl",
		resolve: loadSequence("addvalueservicesAddshowpicCtrl")
	}).state("addvalueservicesAddshowtext", {
		cache: !1,
		url: "/addvalueservicesAddshowtext",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/addvalueservices_addshowtext.html?366",
		controller: "addvalueservicesAddshowtextCtrl",
		resolve: loadSequence("addvalueservicesAddshowtextCtrl")
	}).state("addvalueservicesGoodopinion", {
		cache: !1,
		url: "/addvalueservicesGoodopinion",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/addvalueservices_goodopinion.html?366",
		controller: "addvalueservicesGoodopinionCtrl",
		resolve: loadSequence("addvalueservicesGoodopinionCtrl")
	}).state("addvalueservicesAddgoodopinion", {
		cache: !1,
		url: "/addvalueservicesAddgoodopinion",
		prefetchTemplate: !1,
		templateUrl: "templates/apply/addvalueservices_addgoodopinion.html?366",
		controller: "addvalueservicesAddgoodopinionCtrl",
		resolve: loadSequence("addvalueservicesAddgoodopinionCtrl")
	}).state("integralTest", {
		cache: !1,
		url: "/integralTest",
		prefetchTemplate: !1,
		templateUrl: "templates/helpcenter/integral_test.html?366"
	}).state("update", {
		cache: !1,
		url: "/update",
		prefetchTemplate: !1,
		templateUrl: "templates/login/update.html?226"
	}).state("fundall", {
		cache: !1,
		url: "/fundall",
		prefetchTemplate: !1,
		templateUrl: "templates/funddetail/fundall.html?366",
		controller: "fundallCtrl",
		resolve: loadSequence("fundallCtrl")
	}).state("useVipDredge", {
		cache: !1,
		url: "/useVipDredge",
		prefetchTemplate: !1,
		templateUrl: "templates/funddetail/useVip_dredge.html?366",
		controller: "useVipDredgeCtrl",
		resolve: loadSequence("useVipDredgeCtrl")
	}).state("withdrawBind", {
		cache: !1,
		url: "/withdrawBind",
		prefetchTemplate: !1,
		templateUrl: "templates/funddetail/withdraw_bind.html?366",
		controller: "withdrawBindCtrl",
		resolve: loadSequence("withdrawBindCtrl")
	}).state("withdrawBindsubmit", {
		cache: !1,
		url: "/withdrawBindsubmit",
		prefetchTemplate: !1,
		templateUrl: "templates/funddetail/withdraw_bindsubmit.html?366",
		controller: "withdrawBindsubmitCtrl",
		resolve: loadSequence("withdrawBindsubmitCtrl")
	}).state("withdrawDeposit", {
		cache: !1,
		url: "/withdrawDeposit",
		prefetchTemplate: !1,
		templateUrl: "templates/funddetail/withdraw_deposit.html?366",
		controller: "withdrawDepositCtrl",
		resolve: loadSequence("withdrawDepositCtrl")
	}).state("withdrawIntoaccount", {
		cache: !1,
		url: "/withdrawIntoaccount",
		prefetchTemplate: !1,
		templateUrl: "templates/funddetail/withdraw_intoaccount.html?366",
		controller: "withdrawIntoaccountCtrl",
		resolve: loadSequence("withdrawIntoaccountCtrl")
	}).state("taobaoaccountBind", {
		cache: !1,
		url: "/taobaoaccountBind",
		prefetchTemplate: !1,
		templateUrl: "templates/taobao_bind/taobaoaccount_bind.html?366",
		controller: "taobaoaccountBindCtrl",
		resolve: loadSequence("taobaoaccountBindCtrl")
	}).state("taobaoaccoutReject", {
		cache: !1,
		url: "/taobaoaccoutReject",
		prefetchTemplate: !1,
		templateUrl: "templates/taobao_bind/taobaoaccout_reject.html?366",
		controller: "taobaoaccountBindCtrl",
		resolve: loadSequence("taobaoaccountBindCtrl")
	}).state("taobaoaccoutSucceed", {
		cache: !1,
		url: "/taobaoaccoutSucceed",
		prefetchTemplate: !1,
		templateUrl: "templates/taobao_bind/taobaoaccout_succeed.html?366",
		controller: "taobaoaccountSuccessCtrl",
		resolve: loadSequence("taobaoaccountSuccessCtrl")
	}).state("useVipSucceed", {
		cache: !1,
		url: "/useVipSucceed",
		prefetchTemplate: !1,
		templateUrl: "templates/funddetail/useVip_succeed.html?366"
	}).state("helpcenterIndex", {
		cache: !1,
		url: "/helpcenterIndex",
		prefetchTemplate: !1,
		templateUrl: "templates/helpcenter/helpcenter_index.html?366",
		controller: "helpcenterIndexCtrl",
		resolve: loadSequence("helpcenterIndexCtrl")
	}).state("helpcenterList", {
		cache: !1,
		url: "/helpcenterList",
		prefetchTemplate: !1,
		templateUrl: "templates/helpcenter/helpcenter_list.html?366"
	}).state("helpcenterListA", {
		cache: !1,
		url: "/helpcenterListA",
		prefetchTemplate: !1,
		templateUrl: "templates/helpcenter/helpcenter_lista.html?366"
	}).state("helpcenterListB", {
		cache: !1,
		url: "/helpcenterListB",
		prefetchTemplate: !1,
		templateUrl: "templates/helpcenter/helpcenter_listb.html?366"
	}).state("helpcenterListC", {
		cache: !1,
		url: "/helpcenterListC",
		prefetchTemplate: !1,
		templateUrl: "templates/helpcenter/helpcenter_listc.html?366"
	}).state("helpcenterDetail", {
		cache: !1,
		url: "/helpcenterDetail",
		prefetchTemplate: !1,
		templateUrl: "templates/helpcenter/helpcenter_detail.html?366",
		controller: "helpcenterDetailCtrl",
		resolve: loadSequence("helpcenterDetailCtrl")
	}).state("feedBack", {
		cache: !1,
		url: "/feedBack",
		prefetchTemplate: !1,
		templateUrl: "templates/helpcenter/feedback.html?366",
		controller: "feedBackCtrl",
		resolve: loadSequence("feedBackCtrl")
	}).state("goldDeposits", {
		cache: !1,
		url: "/goldDeposits",
		prefetchTemplate: !1,
		templateUrl: "templates/coindetail/gold_deposits.html?366",
		controller: "goldDepositsCtrl",
		resolve: loadSequence("goldDepositsCtrl")
	}).state("goidIndex", {
		cache: !1,
		url: "/goidIndex",
		prefetchTemplate: !1,
		templateUrl: "templates/coindetail/goid_index.html?366",
		controller: "goidIndexCtrl",
		resolve: loadSequence("goidIndexCtrl")
	}).state("integralList", {
		cache: !1,
		url: "/integralList",
		prefetchTemplate: !1,
		templateUrl: "templates/integration/integral_list.html?366",
		controller: "integralListCtrl",
		resolve: loadSequence("integralListCtrl")
	}).state("newNotice", {
		cache: !1,
		url: "/newNotice",
		prefetchTemplate: !1,
		templateUrl: "templates/helpcenter/new_notice.html?366",
		controller: "newNoticeCtrl",
		resolve: loadSequence("newNoticeCtrl")
	}).state("login", {
		cache: !1,
		url: "/login",
		prefetchTemplate: !1,
		templateUrl: "templates/login/login.html?366",
		controller: "loginCtrl",
		resolve: loadSequence("loginCtrl")
	}).state("loginbind", {
		cache: !1,
		url: "/loginbind",
		prefetchTemplate: !1,
		templateUrl: "templates/login/login_bind.html?366",
		controller: "loginbindCtrl",
		resolve: loadSequence("loginbindCtrl")
	}).state("loginregister", {
		cache: !1,
		url: "/loginregister",
		prefetchTemplate: !1,
		templateUrl: "templates/login/login_register.html?366",
		controller: "loginregisterCtrl",
		resolve: loadSequence("loginregisterCtrl")
	}), $urlRouterProvider.otherwise("/login")
}]);
